# Generated by Django 4.2.3 on 2023-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Istanbul,Turkey', max_length=100),
        ),
    ]
