# Generated by Django 4.2.3 on 2023-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.CharField(max_length=30),
        ),
    ]
