# Generated by Django 4.2.3 on 2023-08-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(blank=True, default='default_food.jpg', null=True, upload_to=''),
        ),
    ]
